<a href="https://colab.research.google.com/github/xariskap/Neural-Network/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np

In [ ]:
class Individual(object):
    def __init__(self, chromosome):
        self.chromosome = chromosome
        self.fitness = self.calculate_fitness()

    @classmethod
    def create_genome(self):

        genome = np.random.randint(0, 1, size=8520)
        rand_ones = random.randint(0, 8519)
        for _ in range(rand_ones):
            genome[random.randint(0, 8519)] = 1
        return genome

    def calculate_fitness(self):
        return 0

In [ ]:
idf = []
tf = []
tf_idf = []
bag_of_words = []
count = 0
with open('/content/drive/MyDrive/Data/train-data.dat') as data:
    for line in data:
        count += 1
        tf_bag = [0 for _ in range(8520)]
        bag = [0 for _ in range(8520)]
        inline = line.strip().split()
        for index, value in enumerate(inline):
            if value[0] != '<':
                bag[int(value)] += 1
      
        bag_of_words.append(bag)
        
        # compute tf
        non_zero = np.count_nonzero(bag)
        for index, value in enumerate(bag):
          tf_bag[index] = value / non_zero
        tf.append(tf_bag)
        print(f'Data {count} completed!')

# compute idf
np.array(bag_of_words)
N = np.size(bag_of_words,0)
M = np.size(bag_of_words,1)
sum_d_t = (np.count_nonzero(bag_of_words, axis=0))


for i in range(M):  
  idf.append( np.log10( N / sum_d_t[i]) )

tf = np.array(tf)
idf = np.array(idf)
print(tf.shape)
print(idf.shape)


# cumpute tf-idf
for list in tf:
  tf_idf.append( list * idf )
  i += 1

tf_idf = np.array(tf_idf)
print(tf_idf.shape)

In [ ]:
# tf_idf_mean
x = np.mean(tf_idf, axis = 0)
print(x.shape)

(8520,)


In [ ]:
def genome_rejection(genome: Individual):
    while np.sum(genome) < 1000:
        genome = Individual.create_genome()
    return genome


def repair_genome(genome: Individual):
    nnz = np.sum(genome)
    while nnz < 1000:
        difference = 1000 - nnz
        for _ in range(difference):
            genome[random.randint(0, 8519)] = 1
        nnz = np.sum(genome)
    return genome


def initialize_population(no_of_chromosomes):
    population = []
    for _ in range(no_of_chromosomes):
        genome = Individual.create_genome()
        # genome = genome_rejection(genome)
        genome = repair_genome(genome)
        population.append(genome)

    return np.array(population)

In [ ]:
def main():
    print(initialize_population(10))


if __name__ == '__main__':
    main()


[[0 0 0 ... 0 0 1]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [1 1 1 ... 0 0 0]
 [1 0 1 ... 1 0 1]
 [0 0 1 ... 0 0 0]]
